const KEY = "nobet-listesi-static-v1";
const months = ["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"];
const today = new Date();
const defaultStaff = ["Abdullah Tecen","Ercan Kurt","Fatih Karabulut","Kutay Hoş","Yusuf Can Özdemir","Bahar Yarenoğlu","Damlanur Köksalan","Hazal Kaşıkcı","Sedanur Demir"].map((name,index)=>({id:crypto.randomUUID(),name,gender:index<5?"male":"female",night:true}));
let state = JSON.parse(localStorage.getItem(KEY) || "null") || {year:today.getFullYear(),month:today.getMonth()+1,staff:defaultStaff,leaves:[],plan:null};
const $ = selector => document.querySelector(selector);
function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
function dateKey(year,month,day){return `${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function daysInMonth(){return new Date(state.year,state.month,0).getDate();}
function leaveSet(date){return new Set(state.leaves.filter(item=>item.date===date).map(item=>item.staffId));}
function count(plan,id,role){return plan.days.reduce((n,day)=>n+(day[role].includes(id)?1:0),0);}
function generate(){const plan={year:state.year,month:state.month,days:[],forced:false,approved:false};let priorNight=null,priorEvening=new Set();const weekly=new Map();for(let number=1;number<=daysInMonth();number++){const date=dateKey(state.year,state.month,number),weekday=new Date(`${date}T00:00:00`).getDay(),unavailable=leaveSet(date),assigned=new Set(),week=Math.floor((number-1)/7);const weekCount=id=>weekly.get(`${week}:${id}`)||0;const choose=(role,filter=()=>true)=>{let choices=state.staff.filter(p=>!unavailable.has(p.id)&&!assigned.has(p.id)&&priorNight!==p.id&&!(role==="morning"&&priorEvening.has(p.id))&&filter(p)&&weekCount(p.id)<5);let forced=false;if(!choices.length){choices=state.staff.filter(p=>!unavailable.has(p.id)&&!assigned.has(p.id)&&filter(p));forced=true;}if(!choices.length)return {id:null,forced:false};choices.sort((a,b)=>{const ac=count(plan,a.id,role),bc=count(plan,b.id,role);return ac-bc||(count(plan,a.id,"morning")+count(plan,a.id,"evening")+count(plan,a.id,"night"))-(count(plan,b.id,"morning")+count(plan,b.id,"evening")+count(plan,b.id,"night"));});const choice=choices[0];assigned.add(choice.id);weekly.set(`${week}:${choice.id}`,weekCount(choice.id)+1);return {id:choice.id,forced};};const morning=[],evening=[],night=[];const morningSlots=weekday===0?1:4;for(let slot=0;slot<morningSlots;slot++){const m=choose("morning",p=>slot!==3||p.gender==="female");morning.push(m.id);plan.forced ||= m.forced;}for(let slot=0;slot<(weekday===0?1:2);slot++){const e=choose("evening");evening.push(e.id);plan.forced ||= e.forced;}const n=choose("night",p=>p.night);night.push(n.id);plan.forced ||= n.forced;plan.days.push({date,weekday,morning,evening,night,forced:n.forced});priorNight=n.id;priorEvening=new Set(evening.filter(Boolean));}state.plan=plan;persist();render();}
function name(id){return state.staff.find(p=>p.id===id)?.name||"—";}
function renderStaff(){const list=$("#staff-list");list.innerHTML="";state.staff.forEach(person=>{const row=$("#staff-template").content.firstElementChild.cloneNode(true);row.querySelector(".staff-name").value=person.name;row.querySelector(".staff-gender").value=person.gender;row.querySelector(".staff-night").checked=person.night;row.querySelector(".staff-name").oninput=e=>{person.name=e.target.value;persist();renderLeaves();};row.querySelector(".staff-gender").onchange=e=>{person.gender=e.target.value;persist();};row.querySelector(".staff-night").onchange=e=>{person.night=e.target.checked;persist();};row.querySelector(".remove").onclick=()=>{state.staff=state.staff.filter(item=>item.id!==person.id);state.leaves=state.leaves.filter(item=>item.staffId!==person.id);persist();render();};list.append(row);});}
function renderLeaves(){const select=$("#leave-staff");select.innerHTML=state.staff.map(p=>`<option value="${p.id}">${p.name}</option>`).join("");const list=$("#leave-list");list.innerHTML=state.leaves.map(item=>`<div class="leave-item"><span>${name(item.staffId)} · ${item.date}</span><button class="secondary" data-id="${item.id}">Sil</button></div>`).join("")||"<span class='muted'>Kayıtlı izin/rapor yok.</span>";list.querySelectorAll("button").forEach(button=>button.onclick=()=>{state.leaves=state.leaves.filter(item=>item.id!==button.dataset.id);persist();render();});}
function renderRisk(){const risks=[];let priorNight=null;for(let day=1;day<=daysInMonth();day++){const date=dateKey(state.year,state.month,day),unavailable=leaveSet(date),count=state.staff.filter(p=>p.night&&!unavailable.has(p.id)&&p.id!==priorNight).length;if(count<3)risks.push(`${date}: ${count} gece adayı`);priorNight=null;}$("#risk").innerHTML=`<div class="risk-card ${risks.length?"":"good"}"><strong>${risks.length?"Gece kapsam riski":"Gece kapsam analizi"}</strong><br>${risks.length?risks.join(" · "):"Mevcut izinler ve gece uygunluklarıyla kritik gün görünmüyor."}</div>`;}
function renderPlan(){const area=$("#schedule"),balance=$("#balance"),approval=$("#approval");if(!state.plan){area.innerHTML="<p class='muted'>Liste oluştur düğmesini kullanın.</p>";balance.innerHTML="";approval.hidden=true;return;}approval.hidden=!state.plan.forced;$("#approve-forced").checked=state.plan.approved;const rows=state.plan.days.map(day=>`<tr><td>${day.date}</td><td class="morning">${day.morning.map(name).join("<br>")}</td><td class="evening">${day.evening.map(name).join("<br>")}</td><td class="night ${day.forced?"forced":""}">${name(day.night[0])}${day.forced?"<br><b>Zorunlu</b>":""}</td></tr>`).join("");area.innerHTML=`<table><thead><tr><th>Tarih</th><th>08:00–16:00</th><th>16:00–24:00</th><th>24:00–08:00</th></tr></thead><tbody>${rows}</tbody></table>`;const stats=state.staff.map(p=>({name:p.name,total:count(state.plan,p.id,"morning")+count(state.plan,p.id,"evening")+count(state.plan,p.id,"night"),morning:count(state.plan,p.id,"morning"),evening:count(state.plan,p.id,"evening"),night:count(state.plan,p.id,"night")}));balance.innerHTML=`<h3>Denge özeti</h3><table><thead><tr><th>Personel</th><th>Toplam</th><th>Sabah</th><th>Akşam</th><th>Gece</th></tr></thead><tbody>${stats.map(s=>`<tr><td>${s.name}</td><td>${s.total}</td><td>${s.morning}</td><td>${s.evening}</td><td>${s.night}</td></tr>`).join("")}</tbody></table>`;}
function render(){ $("#year").value=state.year;$("#month").value=state.month;renderStaff();renderLeaves();renderRisk();renderPlan();}
function csv(){if(!state.plan)return;const rows=[["Tarih","Sabah","Akşam","Gece"],...state.plan.days.map(d=>[d.date,d.morning.map(name).join(" / "),d.evening.map(name).join(" / "),name(d.night[0])])];const blob=new Blob([rows.map(r=>r.map(v=>`"${v}"`).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`nobet-${state.year}-${state.month}.csv`;a.click();}
months.forEach((name,index)=>$("#month").insertAdjacentHTML("beforeend",`<option value="${index+1}">${name}</option>`));$("#year").onchange=e=>{state.year=Number(e.target.value);persist();renderRisk();};$("#month").onchange=e=>{state.month=Number(e.target.value);persist();renderRisk();};$("#add-staff").onclick=()=>{state.staff.push({id:crypto.randomUUID(),name:"Yeni personel",gender:"female",night:true});persist();render();};$("#leave-form").onsubmit=e=>{e.preventDefault();state.leaves.push({id:crypto.randomUUID(),staffId:$("#leave-staff").value,date:$("#leave-date").value});persist();render();};$("#generate").onclick=generate;$("#save-plan").onclick=()=>{if(state.plan?.forced&&!state.plan.approved){alert("Zorunlu atamalar için onay kutusunu işaretleyin.");return;}persist();alert("Tarayıcıya kaydedildi.");};$("#approve-forced").onchange=e=>{if(state.plan){state.plan.approved=e.target.checked;persist();}};$("#download-csv").onclick=csv;$("#export-data").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="nobet-listesi-yedek.json";a.click();};$("#import-data").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);persist();render();}catch{alert("Dosya okunamadı.");}};reader.readAsText(file);};render();
