import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { trpc } from "@/lib/trpc";
import type { SchedulePlan } from "../../../shared/scheduling";
import { CheckCircle2, Clock3, History, Loader2, RotateCcw, Save, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function DraftActions({ year, month, plan, isDirty, generating, saving, onGenerate, onSave, onRestored }: { year: number; month: number; plan: SchedulePlan | null; isDirty: boolean; generating: boolean; saving: boolean; onGenerate: () => void; onSave: () => void; onRestored: (plan: SchedulePlan) => void }) {
  const [historyOpen, setHistoryOpen] = useState(false);
  const versions = trpc.schedule.versions.useQuery({ year, month }, { enabled: historyOpen });
  const utils = trpc.useUtils();
  const restore = trpc.schedule.restoreVersion.useMutation({ onSuccess: async data => { if (data) onRestored(data.plan); await utils.schedule.get.invalidate({ year, month }); await utils.schedule.versions.invalidate({ year, month }); setHistoryOpen(false); toast.success("Seçilen sürüm geri yüklendi."); }, onError: error => toast.error(error.message) });
  const createNew = () => { if (!isDirty || window.confirm("Kaydedilmemiş taslak silinecek. Yeni bir taslak oluşturmak istiyor musunuz?")) onGenerate(); };
  return <div className="fixed bottom-5 left-1/2 z-40 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 flex-wrap items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-[0_16px_40px_rgba(23,50,77,.18)] backdrop-blur"><span className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-xs font-semibold ${isDirty ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-700"}`}>{isDirty ? <Clock3 className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}{isDirty ? "Kaydedilmemiş taslak" : "Kaydedilmiş"}</span><Button size="sm" variant="outline" disabled={generating} onClick={createNew}>{generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Yeni liste</Button><Button size="sm" disabled={!plan || saving || !isDirty} onClick={onSave}>{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Taslağı kaydet</Button><Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><History className="mr-2 h-4 w-4" />Sürümler</Button></DialogTrigger><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Çizelge sürüm geçmişi</DialogTitle><DialogDescription>Her kaydetme işleminden önceki çizelge sürümü burada saklanır. Geri yüklemek, mevcut listeyi yeni bir sürüm olarak arşivler.</DialogDescription></DialogHeader><ScrollArea className="max-h-[400px] pr-3">{versions.isLoading ? <div className="py-8 text-center text-sm text-slate-500">Sürümler yükleniyor…</div> : !versions.data?.length ? <div className="py-8 text-center text-sm text-slate-500">Bu ay için önceki bir sürüm bulunmuyor.</div> : <div className="grid gap-2">{versions.data.map((version, index) => <div key={version.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="text-sm font-semibold text-slate-800">Sürüm {versions.data!.length - index}</p><p className="mt-1 text-xs text-slate-500">{new Date(version.createdAt).toLocaleString("tr-TR")}</p></div><Button size="sm" variant="outline" disabled={restore.isPending} onClick={() => restore.mutate({ id: version.id })}><RotateCcw className="mr-2 h-3.5 w-3.5" />Geri yükle</Button></div>)}</div>}</ScrollArea></DialogContent></Dialog></div>;
}
